### ISSUE TITLE
Final Tutorial tool tip doesn't disappear after dragging around.

### ISSUE THREAD

**Issue by BryceDerriso** [cityofaustin/transportation-dockless-dataviz#77]
The final tool tip being "Click & drag here to tilt the map".
I did so, and it was still hanging around.

**Comment by mateoclarke** [comment]
Thanks @BryceDerriso, can you provide some more info on the OS & Browser you are using?

**Comment by BryceDerriso** [comment]
Firefox 63.0.1 on Fedora 29.
I'll be checking on IE6 and Windows 95 next.

**Comment by mateoclarke** [comment]
Doubt the map will work on IE6. MapboxGL relies on newer browser tech. So don't think we plan to support that far back.

**Comment by BryceDerriso** [comment]
The tutorial *is* cleared on Chromium in Fedora.
Would be curious to know if Firefox does this on Windows/Mac.
