### ISSUE TITLE
Multiple legends are displayed after flow or mode change

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation-dockless-dataviz#78]
When I change the **flow** or **mode** selectors, a new legend is displayed in the side panel below the old one.

To reproduce: 
1. Draw a point/ploy and let the map/legend draw
2. Change **flow** or **mode** selectors

**Comment by mateoclarke** [comment]
Thanks for logging this issue @johnclary. We saw this on Wednesday at Open Austin Community Action Night but I forgot to log it.
