### ISSUE TITLE
Date filters are not applied if edited via keyboard

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation-dockless-dataviz#92]
Changes to the Start/End Date filter are not applied to trip query if they are edited by keyboard input (rather than selected from the calendar menu).

To reproduce:
1. Load app
2. Click on Start Date input and use keyboard to replace 01/01/2018 with 01/01/2019. 
3. Drop a pin.

Inspection of the API call reveals that the start date is submitted as 01/01/2018 (1514786400000).

<img width="521" alt="screen shot 2019-01-08 at 10 11 10 pm" src="https://user-images.githubusercontent.com/14793120/50876421-90fa8180-1392-11e9-9003-0a9a750adace.png">

**Comment by mateoclarke** [comment]
Good find! This should be hours not days of work and have labeled as such. Should I prioritize fixing this sprint or next @johnclary ?
